### ISSUE TITLE
Getting warning when using latest stable version (1.4.0)

### ISSUE THREAD

**Issue by HarelM** [NetTopologySuite/ProjNet4GeoAPI#35] opened 2018-08-28 20:52 UTC
Hi, I'm getting the following warning when using this library:
```
warning NU1602: ProjNET4GeoAPI 1.4.0 does not provide an inclusive lower bound for dependency GeoAPI.CoordinateSystems. An approximate best match of GeoAPI.CoordinateSystems 1.7.5 was resolved.
```

Probably an easy fix, right?

**Comment by airbreather** [comment] 2018-08-28 21:09
Duplicate of #34

**Closed by airbreather** 2018-08-28 21:09 UTC

**Comment by HarelM** [comment] 2018-08-28 21:15
Sorry, miss-read that issue...
